# Site settings
title: Gray Bike
email: pavan@graybike.co
description: "No nonsense software design, development, and consulting."
baseurl: ""
url: "http://graybike.co"

# Build settings
markdown: kramdown
permalink: pretty
