# Site settings
title: GRAY BIKE
email: pavan@graybike.co
description: "Software design, engineering, and consulting."
baseurl: ""
url: "http://graybike.co"

# Build settings
markdown: kramdown
permalink: pretty
